apps/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home_page, name="home_page"),
]

apps/contacts/urls.py
from django.urls import path

from apps.contacts import views

app_name = "contacts"

urlpatterns = [
    path("list/", views.ContactsListView.as_view(), name="contact_list"),
    path("create/", views.ContactCreateView.as_view(), name="contacts_create"),
    path("update/<int:pk>/", views.ContactUpdateView.as_view(), name="contacts_update"),
    path("delete/<int:pk>/", views.ContactDeleteView.as_view(), name="contacts_delete"),
    path("delete/", views.delete_all_contacts_view, name="contacts_delete"),
]

apps/first_example/urls.py
from django.urls import path, include

from . import views

app_name = "first_example"

urlpatterns = [
    path("hi/<name>/<int:age>/", views.GreetingsView.as_view(), name="greetings"),
    path(
        "generate-humans/",
        include(
            [
                path("<int:amount>/", views.generate_humans_view, name="generate_humans_with_amount"),
                path("", views.generate_humans_view, name="generate_humans"),
            ]
        ),
    ),
]

apps/homework/urls.py
from django.urls import path, include

from apps.homework import views

app_name = "homework"

urlpatterns = [
    path(
        "generate-humans/",
        include(
            [
                path("<int:amount>/", views.GenerateHumansView.as_view(), name="generate_humans_with_amount"),
                path("", views.GenerateHumansView.as_view(), name="generate_humans"),
            ]
        ),
    ),
]

core/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("apps.base.urls")),
    path("", include("apps.homework.urls")),
    path("contacts/", include("apps.contacts.urls")),
]

homework__kubarev_aleksey__11/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/animals/models/animal.py
from django.db import models


class Animal(models.Model):
    name = models.CharField(max_length=100)
    age = models.PositiveSmallIntegerField(
        blank=True,
        default=0,
    )

    is_auto_generated = models.BooleanField(
        blank=False,
        default=False,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return f"{self.name}"

    __repr__ = __str__

    class Meta:
        ordering = ["modified_at", "name"]

apps/contacts/models/contact.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)

    is_auto_generated = models.BooleanField(
        blank=False,
        default=False,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return f"{self.name}"

    __repr__ = __str__

    class Meta:
        ordering = ["modified_at", "name"]

apps/contacts/models/contacts.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return f"{self.name}"

    __repr__ = __str__

    class Meta:
        ordering = ["-modified_at", "name"]

apps/base/views.py
from django.shortcuts import render
from datetime import datetime


def home_page(request):
    time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return render(
        request=request,
        template_name="base/home_page.html",
        context={
            "greetings_text": f"Welcome! This is the homepage of homework №13." f"The current time in Kyiv is: {time}",
            "title": "Home page",
        },
    )

apps/contacts/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.contacts.models import Contact
from apps.contacts.services.delete_all_contacts import delete_all_contacts


class ContactsListView(ListView):
    model = Contact


class ContactCreateView(CreateView):
    model = Contact
    fields = (
        "name",
        "phone",
    )

    success_url = reverse_lazy("contacts:contact_list")


class ContactUpdateView(UpdateView):
    model = Contact
    fields = (
        "name",
        "phone",
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context

    success_url = reverse_lazy("contacts:contact_list")


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = reverse_lazy("contacts:contact_list")


def delete_all_contacts_view(request):
    delete_all_contacts()

    return redirect(reverse_lazy("contacts:contact_list"))

apps/first_example/views/generate_humans.py
from django.shortcuts import render

from apps.first_example.services.generate_humans import generate_humans


def generate_humans_view(
    request,
    amount: int = 5,
):
    humans = generate_humans(amount=amount)

    return render(
        request=request,
        template_name="first_example/generate_humans.html",
        context=dict(
            humans=humans,
        ),
    )

apps/first_example/views/greetings.py
from django.views.generic import TemplateView


# def greetings(request, name: str, age: int):
#     return render(
#         request=request,
#         template_name="first_example/greetings.html",
#         context={
#             "name": name,
#             "age": age,
#             #
#             "title": "Greetings",
#         },
#     )


class GreetingsView(TemplateView):
    template_name = "first_example/greetings.html"

    def get_context_data(self, name: str, age: int, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update(
            name=name,
            age=age,
            #
            title="Greetings",
        )

        return context

apps/homework/views/generate_humans.py
from django.views.generic import TemplateView

from apps.homework.services.generate_humans import generate_humans


class GenerateHumansView(TemplateView):
    template_name = "homework/generate_humans.html"

    def get_context_data(self, amount: int = 25, **kwargs):
        context = super().get_context_data(**kwargs)

        humans = generate_humans(amount=amount)

        context.update(
            humans=humans,
        )

        return context

apps/templates/_helpers/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% endif %}
                Welcome!
        {% endblock %}
    </title>
    <style>
        html {
            height: 100%;
        }

        body {
            min-height: 100%;
            margin: 0;
            padding: 0;
            position: relative;
        }

        .background {
            background: linear-gradient(132deg, #FC415A, #591BC5, #212335);
            background-size: 400% 400%;
            animation: Gradient 15s ease infinite;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            z-index: -1;
        }

        .cube {
            position: absolute;
            top: 80vh;
            left: 45vw;
            width: 10px;
            height: 10px;
            border: solid 1px #D7D4E4;
            transform-origin: top left;
            transform: scale(0) rotate(0deg) translate(-50%, -50%);
            animation: cube 12s ease-in forwards infinite;
        }

        .cube:nth-child(2n) {
            border-color: #FFF;
        }

        .cube:nth-child(2) {
            animation-delay: 2s;
            left: 25vw;
            top: 40vh;
        }

        .cube:nth-child(3) {
            animation-delay: 4s;
            left: 75vw;
            top: 50vh;
        }

        .cube:nth-child(4) {
            animation-delay: 6s;
            left: 90vw;
            top: 10vh;
        }

        .cube:nth-child(5) {
            animation-delay: 8s;
            left: 10vw;
            top: 85vh;
        }

        .cube:nth-child(6) {
            animation-delay: 10s;
            left: 50vw;
            top: 10vh;
        }

        @keyframes Gradient {
            0% {
                background-position: 0% 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }

        @keyframes cube {
            from {
                transform: scale(0) rotate(0deg) translate(-50%, -50%);
                opacity: 1;
            }
            to {
                transform: scale(20) rotate(960deg) translate(-50%, -50%);
                opacity: 0;
            }
        }
    </style>
</head>
<body>
<div class="background">
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
</div>

{% include "_helpers/_header.html" %}

<div>
    {% block content %}
        <h1>Hello!</h1>
    {% endblock %}
</div>

</body>
</html>

apps/templates/_helpers/_header.html
<header>
    <div><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" data-name="Layer 1" id="python"><path d="M20.08 23.41h7.54a5 5 0 0 0 4.84-4.05V10.2s-1.81-4-9.11-4-8.54 3.35-8.54 3.35v4.71h8.83V16H11.88a6.21 6.21 0 0 0-6.25 6.22v5.16a5.45 5.45 0 0 0 5.45 5.46H14v-3.36a6.06 6.06 0 0 1 6.08-6.07ZM18.72 12a1.51 1.51 0 1 1 1.51-1.51A1.52 1.52 0 0 1 18.72 12Z"></path><path d="M36.92 15.17H34v3.35a6.06 6.06 0 0 1-6.06 6.07h-7.56a5 5 0 0 0-4.84 4.05v9.16s1.81 4 9.11 4 8.54-3.35 8.54-3.35v-4.68h-8.83V32h11.76a6.21 6.21 0 0 0 6.25-6.22v-5.15a5.45 5.45 0 0 0-5.45-5.46ZM29.28 36a1.51 1.51 0 1 1-1.51 1.51A1.52 1.52 0 0 1 29.28 36Z"></path></svg></div>


    <ul>
        <li>
            <a href="{% url 'base:home_page' %}" style="color: GhostWhite">
                Home
            </a>
        </li>
        <li>
            <a href="{% url 'homework:generate_humans' %}" style="color: GhostWhite">
                Generate humans
            </a>
        </li>
                <li>
            <a href="{% url 'contacts:contact_list' %}" style="color: GhostWhite">
                Contacts list
            </a>
        </li>
    </ul>
</header>

apps/templates/base/home_page.html
{% extends "_helpers/_base.html" %}


{% block title %}
    {{ title }} :)
{% endblock %}


{% block content %}
    <div style="color: White; padding-left: 20px;">
    <p>{{ greetings_text }}</p>
    </div>
{% endblock %}

apps/templates/contacts/_contacts_list_base.html
<div style="color: White; padding-left: 20px;">
    <div>
        <a href="{% url 'contacts:contacts_create' %}">
            <button>Create new contact</button>
        </a>
        <a href="{% url 'contacts:contacts_delete' %}">
            <button>Delete all contacts</button>
        </a>
    </div>

    <ol>
        {% for contact in contacts_list %}
            <li>
                <div style="display: flex; flex-flow: row;">
                    <div style="margin: .2em;">
                        <b><span>{{ contact.name }}</span></b>
                        <span>{{ contact.phone }}</span>
                        <br>
                        <span>{{ contact.modified_at }}</span>
                    </div>
                    <div style="margin: .2em;">
                        <a href="{% url 'contacts:contacts_update' contact.pk %}">
                            <button>Update</button>
                        </a>
                        <a href="{% url 'contacts:contacts_delete' contact.pk %}">
                            <button>Delete</button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ol>
</div>

apps/templates/contacts/contact_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p style="color: White; padding-left: 20px;">Are you sure you want to delete "{{ object }}"?</p>
        <div style="color: White; padding-left: 20px;">
            {{ form }}
            <input type="submit" value="Confirm">
        </div>
    </form>
{% endblock %}

apps/templates/contacts/contact_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>
        {% if is_update %}
            Update
        {% else %}
            Create
        {% endif %}
        contact
    </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            {% if is_update %}
                Update
            {% else %}
                Create
            {% endif %}
        </button>
    </form>
{% endblock %}

apps/templates/contacts/contact_list.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Contact</h1>

{% include "contacts/_contacts_list_base.html" with contacts_list=object_list %}

{% endblock %}

apps/templates/contacts/contacts_create.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Create</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
{% endblock %}

apps/templates/first_example/generate_humans.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Humans</h1>
    <ol>
        {% for human in humans %}
            <li>
                <span>{{ human.name }}</span>
                <span> - </span>
                <span>{{ human.age }}</span>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

apps/templates/first_example/greetings.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <p>Hello, {{ name }}! You are {{ age }} years old!</p>
{% endblock %}

apps/templates/homework/generate_humans.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <div style="color: White; padding-left: 20px;">
        <h1>Humans</h1>
        <div style="flex-wrap: wrap;">
            {% for human in humans %}
                <div style="margin-bottom: 20px;">
                    <span>Human №{{ forloop.counter }}</span>
                    <br>
                    <span>Username: {{ human.username }}</span>
                    <br>
                    <span>Email: {{ human.email }}</span>
                    <br>
                    <span>Password: {{ human.password }}</span>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}